In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Data visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import cm

# Text Mining
import nltk
nltk.download('punkt')
from wordcloud import WordCloud
from collections import Counter
nltk.download('stopwords')
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('punkt_tab')

# warning management library
import warnings

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\smazo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\smazo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\smazo\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\smazo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [2]:
warnings.filterwarnings('ignore')
sns.set()
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

### 1. Loading of MSPT dataset and imbd titles

In [3]:
mpst = pd.read_csv("../Raw_Data/mpst_full_data.csv")
# https://www.kaggle.com/datasets/cryptexcode/mpst-movie-plot-synopses-with-tags?resource=download

In [4]:
mpst.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14828 entries, 0 to 14827
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   imdb_id          14828 non-null  object
 1   title            14828 non-null  object
 2   plot_synopsis    14828 non-null  object
 3   tags             14828 non-null  object
 4   split            14828 non-null  object
 5   synopsis_source  14828 non-null  object
dtypes: object(6)
memory usage: 695.2+ KB

In [5]:
mpst.head()

     imdb_id                                          title                                      plot_synopsis                                               tags  split synopsis_source
0  tt0057603                        I tre volti della paura  Note: this synopsis is for the orginal Italian...          cult, horror, gothic, murder, atmospheric  train            imdb
1  tt1733125  Dungeons & Dragons: The Book of Vile Darkness  Two thousand years ago, Nhagruul the Foul, a s...                                           violence  train            imdb
2  tt0033045                     The Shop Around the Corner  Matuschek's, a gift store in Budapest, is the ...                                           romantic   test            imdb
3  tt0113862                             Mr. Holland's Opus  Glenn Holland, not a morning person by anyone'...             inspiring, romantic, stupid, feel-good  train            imdb
4  tt0086250                                       Scarface  In May 1980, a Cuban man named Tony Montana (A...  cruelty, murder, dramatic, cult, violence, atm...    val            imdb

In [6]:
mpst.iloc[0,2]

'Note: this synopsis is for the orginal Italian release with the segments in this certain order.Boris Karloff introduces three horror tales of the macabre and the supernatural known as the \'Three Faces of Fear\'.THE TELEPHONERosy (Michele Mercier) is an attractive, high-priced Parisian call-girl who returns to her spacious, basement apartment after an evening out when she immediately gets beset by a series of strange phone calls. The caller soon identified himself as Frank, her ex-pimp who has recently escaped from prison. Rosy is terrified for it was her testimony that landed the man in jail. Looking for solace, Rosy phones her lesbian lover Mary (Lynda Alfonsi). The two women have been estranged for some time, but Rosy is certain that she is the only one who can help her. Mary agrees to come over that night. Seconds later, Frank calls again, promising that no matter who she calls for protection, he will have his revenge. Unknown to Rosy, Mary is the caller impersonating Frank. Marry arrives at Rosy\'s apartment soon after, and does her best to calm Rosy\'s nerves. She gives the panic-struck woman a tranquillizer and puts her to bed.Later that night as Rosy sleeps, Mary gets up out of bed, and pens a note of confession: she was the one making the strange phone calls when she learned of Franks escape from prison. Knowing that Rosy would call on her for help, she explains that she felt it was her way of coming back into her life after their breakup. While she is busy writing, she fails to notice an intruder in the apartment. This time it is Frank, for real. He creeps up behind Mary and strangles her to death with one of Rosys nylon stockings. The sound of the struggle awaken Rosy and she gasps in fright. The murderous pimp realizes that he just killed the wrong woman, and slowly makes his way to Rosy\'s bed. However, earlier that night, Rosy had placed a butcher knife under her pillow at Mary\'s suggestion. Rosy seizes the knife and stabs Frank with it as he\'s beginning to strangle her. Rosy drops the knife and breaks down in hysteria, surrounded by the two corpses of her former lovers.THE WURDALAKIn 19th Century Russia, Vladimir D\'Urfe is a young nobleman on a long trip. During the course of his journey, he finds a beheaded corpse with a knife plunged into its heart. He withdraws the blade and takes it as a souvenir.Later that night, Vladimir stops at a small rural cottage to ask for shelter. He notices several daggers hanging up on one of the walls, and a vacant space that happens to fit the one he has discovered. Vladimir is surprised by the entrance of Giorgio (Glauco Onorato), who explains that the knife belongs to his father, who has not been seen for five days. Giorgio offers a room to the young count, and subsequently introduces him to the rest of the family: his wife (Rika Dialina), their young son Ivan, Giorgio\'s younger brother Pietro (Massimo Righi), and sister Sdenka (Susy Anderson). It subsequently transpires that they are eagerly anticipating the arrival of their father, Gorcha, as well as the reason for his absence: he has gone to do battle with the outlaw and dreaded wurdalak Ali Beg. Vladimir is confused by the term, and Sdenka explains that a wurdalak is a walking cadaver who feeds on the blood of the living, preferably close friends and family members. Giorgio and Pietro are certain that the corpse Vladimir had discovered is that of Ali Beg, but also realize that there is a strong possibility that their father has been infected by the blood curse too. They warn the count to leave, but he decides to stay and await the old mans return.At the stroke of midnight, Gorcha (Boris Karloff) returns to the cottage. His sour demeanor and unkempt appearance bode the worse, and the two brothers are torn: they realize that it is their duty to kill Gorcha before he feeds on the family, but their love for him makes it difficult to reach a decision. Later that night, both Ivan and Pietro are attacked by Gorcha who drains them of blood, and then flees the cottage. Giorgio stakes and beheads Pietro to prevent him from reviving as a wurdalak. But he is prevented from doing so to Ivan when his wife threatens to commit suicide. Reluntantly, he agrees to bury the child without taking the necessary precautions.That same night, the child rises from his grave and begs to be invited into the cottage. The mother runs to her son\'s aid, stabbing Giorgio when he attempts to stop her, only to be greeted at the front door by Gorcha. The old man bits and infects his daughter-in-law, who then does the same for her husband. Vladimir and Sdenka flee from the cottage and go on the run and hide out in the ruins of an abandoned cathedral as dawn breaks. Vladimir is optimistic that a long and happy life lies with them. But Sdenka is reluctant to relinquish her family ties. She believes that she is meant to stay with the family.Sdenka\'s fears about her family are confirmed when that evening, Gorcha and her siblings show up at the abandoned Abby. As Vladimir sleeps, Sdenka is lured into their loving arms where they bite to death. Awakened by her screams, Vladimir rushes to her aid, but the family has already taken her home, forcing the lover to follow suite. The young nobleman finds her, lying motionless on her bed. Sdenka awakens, and a distinct change is visible on her face. No longer caring, Vladimir embraces her, and she bites and infects him too.THE DROP OF WATERIn Victorian London, England, Nurse Helen Chester (Jacqueline Pierreux) is called to a large house to prepare the corpse of an elderly medium for her burial. As she dressed the body, she notices an elaborate diamond ring on its finger. Tempted by greed, Nurse Chester steals it. As she does, a glass tips over, and drops of water begin to splash on the floor. She is also assailed by a fly, no doubt attracted by the odor of the body. Unsettled but pleased by her acquisition, she finishes the job and returns home to her small East End flat.After returning home, Nurse Chester is assailed by strange events. The buzzing fly returns and continues to pester her. Then the lights in her apartment go out, and the sounds of the dripping water continues with maddening regularity. She sees the old womans corpse lying on her bed, and coming towards her. The terrified woman begs for forgiveness, but she ultimately strangles herself, imaging that the medium\'s hands are gripping her throat.The next morning, the concierge (Harriet White Medin) discovers Nurse Chester\'s body and calls the police. The investigator on the scene (Gustavo de Nardo) quickly concludes that its a simple case and that Nurse Chester "died of fright". The pathologist arrives on the scene to examine the body before it\'s taken away and he notes that the only sign of violence is a small bruise on her left finger, mostly likely caused when someone pried a ring from her finger. As the doctor makes this observation, the concierge appears distressed, as she has apparently took the ring from the dead Nurse Chester, and is further distracted by the sound of a fly swooping about in the air....Boris Karloff makes a final appearance as Gorcha riding on his horse as he concludes the three tales of fear and tells the viewers to be careful while walking home at night for ghosts and vampires have no fear. The image pulls back to actually reveal him sitting on a prop fake horse with a camera crew and various crewmen moving branches around to simulate the scene of riding through the forest from the Wurdalak segment.'

In [7]:
mpst_short = mpst[["imdb_id","plot_synopsis", "tags"]]

In [8]:
titles = pd.read_csv("../Raw_Data/title.basics.tsv", sep='\t') #, nrows = 10000)
#https://developer.imdb.com/non-commercial-datasets/

In [9]:
titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12536830 entries, 0 to 12536829
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   tconst          object
 1   titleType       object
 2   primaryTitle    object
 3   originalTitle   object
 4   isAdult         int64
 5   startYear       object
 6   endYear         object
 7   runtimeMinutes  object
 8   genres          object
dtypes: int64(1), object(8)
memory usage: 860.8+ MB

In [10]:
titles.head()

      tconst titleType            primaryTitle           originalTitle  isAdult startYear endYear runtimeMinutes                    genres
0  tt0000001     short              Carmencita              Carmencita        0      1894      \N              1         Documentary,Short
1  tt0000002     short  Le clown et ses chiens  Le clown et ses chiens        0      1892      \N              5           Animation,Short
2  tt0000003     short            Poor Pierrot          Pauvre Pierrot        0      1892      \N              5  Animation,Comedy,Romance
3  tt0000004     short             Un bon bock             Un bon bock        0      1892      \N             12           Animation,Short
4  tt0000005     short        Blacksmith Scene        Blacksmith Scene        0      1893      \N              1                     Short

In [11]:
titles_short = titles[["tconst", "primaryTitle", "genres"]]

In [12]:
movies = titles_short.merge(mpst_short, left_on="tconst", right_on="imdb_id")
movies.head()

      tconst                primaryTitle                    genres    imdb_id                                      plot_synopsis                   tags
0  tt0000091      The House of the Devil              Horror,Short  tt0000091  The film opens with a large bat flying into a ...     paranormal, gothic
1  tt0000225        Beauty and the Beast    Family,Fantasy,Romance  tt0000225  A widower merchant lives in a mansion with his...                fantasy
2  tt0000230                  Cinderella      Drama,Family,Fantasy  tt0000230  A prologue in front of the curtain, suppressed...                fantasy
3  tt0000417          A Trip to the Moon  Adventure,Comedy,Fantasy  tt0000417  At a meeting of the Astronomic Club, its presi...    psychedelic, satire
4  tt0000488  The Land Beyond the Sunset       Drama,Fantasy,Short  tt0000488  Joe is an impoverished New York newsboy who li...  fantasy, storytelling

In [13]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14807 entries, 0 to 14806
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   tconst         14807 non-null  object
 1   primaryTitle   14807 non-null  object
 2   genres         14807 non-null  object
 3   imdb_id        14807 non-null  object
 4   plot_synopsis  14807 non-null  object
 5   tags           14807 non-null  object
dtypes: object(6)
memory usage: 694.2+ KB

In [15]:
movies["genres"] = movies["genres"].apply(lambda x: x.replace(",", " "))
movies["tags"] = movies["tags"].apply(lambda x: x.replace(",", ""))

In [16]:
movies.to_csv("../Transformed_Data/movies_info.csv", index=None)

In [17]:
movies.head()

      tconst                primaryTitle                    genres    imdb_id                                      plot_synopsis                  tags
0  tt0000091      The House of the Devil              Horror Short  tt0000091  The film opens with a large bat flying into a ...     paranormal gothic
1  tt0000225        Beauty and the Beast    Family Fantasy Romance  tt0000225  A widower merchant lives in a mansion with his...               fantasy
2  tt0000230                  Cinderella      Drama Family Fantasy  tt0000230  A prologue in front of the curtain, suppressed...               fantasy
3  tt0000417          A Trip to the Moon  Adventure Comedy Fantasy  tt0000417  At a meeting of the Astronomic Club, its presi...    psychedelic satire
4  tt0000488  The Land Beyond the Sunset       Drama Fantasy Short  tt0000488  Joe is an impoverished New York newsboy who li...  fantasy storytelling