In [4]:
# Data manipulation
import pandas as pd
import numpy as np


# Data visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import cm

# math library
import math
import statistics

# warning management library
import warnings

# DOS like library
import os

# Date management
from datetime import *
from dateutil.relativedelta import *
from dateutil.parser import *


# Images analysis
from PIL import Image
from PIL import ImageOps

# Text Mining
import nltk
nltk.download('punkt')
from wordcloud import WordCloud
from collections import Counter
nltk.download('stopwords')
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

# Machine learning
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\smazo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\smazo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\smazo\AppData\Roaming\nltk_data...

In [5]:
warnings.filterwarnings('ignore')
sns.set()
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

### Loading of file title.basics.tz

In [ ]:
titles = pd.read_csv("../Raw_Data/title.basics.tsv", sep='\t', nrows = 10000)

In [10]:
titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tconst          10000 non-null  object
 1   titleType       10000 non-null  object
 2   primaryTitle    10000 non-null  object
 3   originalTitle   10000 non-null  object
 4   isAdult         10000 non-null  int64
 5   startYear       10000 non-null  object
 6   endYear         10000 non-null  object
 7   runtimeMinutes  10000 non-null  object
 8   genres          10000 non-null  object
dtypes: int64(1), object(8)
memory usage: 703.3+ KB

In [11]:
titles.head()

      tconst titleType            primaryTitle           originalTitle  isAdult startYear endYear runtimeMinutes                    genres
0  tt0000001     short              Carmencita              Carmencita        0      1894      \N              1         Documentary,Short
1  tt0000002     short  Le clown et ses chiens  Le clown et ses chiens        0      1892      \N              5           Animation,Short
2  tt0000003     short            Poor Pierrot          Pauvre Pierrot        0      1892      \N              5  Animation,Comedy,Romance
3  tt0000004     short             Un bon bock             Un bon bock        0      1892      \N             12           Animation,Short
4  tt0000005     short        Blacksmith Scene        Blacksmith Scene        0      1893      \N              1                     Short

In [12]:
titles_reduced = titles[["tconst", "primaryTitle", "genres"]]

In [14]:
titles_reduced.head()

      tconst            primaryTitle                    genres
0  tt0000001              Carmencita         Documentary,Short
1  tt0000002  Le clown et ses chiens           Animation,Short
2  tt0000003            Poor Pierrot  Animation,Comedy,Romance
3  tt0000004             Un bon bock           Animation,Short
4  tt0000005        Blacksmith Scene                     Short