In [36]:
# Data manipulation
import pandas as pd
import numpy as np


# Data visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import cm

# math library
import math
import statistics

# warning management library
import warnings

# DOS like library
import os

# Date management
from datetime import *
from dateutil.relativedelta import *
from dateutil.parser import *


# Images analysis
from PIL import Image
from PIL import ImageOps

# Text Mining
import nltk
nltk.download('punkt')
from wordcloud import WordCloud
from collections import Counter
nltk.download('stopwords')
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('punkt_tab')

# Machine learning
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\smazo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\smazo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\smazo\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\smazo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [37]:
warnings.filterwarnings('ignore')
sns.set()
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

### Loading of file title.basics.tz

In [38]:
titles = pd.read_csv("../Raw_Data/title.basics.tsv", sep='\t', nrows = 10000)

In [39]:
titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tconst          10000 non-null  object
 1   titleType       10000 non-null  object
 2   primaryTitle    10000 non-null  object
 3   originalTitle   10000 non-null  object
 4   isAdult         10000 non-null  int64
 5   startYear       10000 non-null  object
 6   endYear         10000 non-null  object
 7   runtimeMinutes  10000 non-null  object
 8   genres          10000 non-null  object
dtypes: int64(1), object(8)
memory usage: 703.3+ KB

In [40]:
titles.head()

      tconst titleType            primaryTitle           originalTitle  isAdult startYear endYear runtimeMinutes                    genres
0  tt0000001     short              Carmencita              Carmencita        0      1894      \N              1         Documentary,Short
1  tt0000002     short  Le clown et ses chiens  Le clown et ses chiens        0      1892      \N              5           Animation,Short
2  tt0000003     short            Poor Pierrot          Pauvre Pierrot        0      1892      \N              5  Animation,Comedy,Romance
3  tt0000004     short             Un bon bock             Un bon bock        0      1892      \N             12           Animation,Short
4  tt0000005     short        Blacksmith Scene        Blacksmith Scene        0      1893      \N              1                     Short

In [41]:
titles_reduced = titles[["tconst", "primaryTitle", "genres"]]

In [42]:
titles_reduced.head()

      tconst            primaryTitle                    genres
0  tt0000001              Carmencita         Documentary,Short
1  tt0000002  Le clown et ses chiens           Animation,Short
2  tt0000003            Poor Pierrot  Animation,Comedy,Romance
3  tt0000004             Un bon bock           Animation,Short
4  tt0000005        Blacksmith Scene                     Short

In [43]:
titles_reduced.rename(columns={"primaryTitle": "title"}, inplace=True)
titles_reduced["genres"] = titles_reduced["genres"].apply(lambda x: x.replace(",", " "))
titles_reduced.head()

      tconst                   title                    genres
0  tt0000001              Carmencita         Documentary Short
1  tt0000002  Le clown et ses chiens           Animation Short
2  tt0000003            Poor Pierrot  Animation Comedy Romance
3  tt0000004             Un bon bock           Animation Short
4  tt0000005        Blacksmith Scene                     Short

### 1. Starting Natural Language Processing

#### 1.1 Lemmatization and Tokenization

In [44]:
# list of french stopwords : https://www.ranks.nl/stopwords/french
french_stopwords = ["alors","au","aucun","aussi","autre","avant","avec","avoir","bon","car","ce","cela","ces","ceux","chaque","ci",
                    "comme","comment","dans","des","du",
"dedans","dehors","depuis","devrait","doit","donc","début","elle","elles","en","encore","essai","est","et","eu","fait","faites",
"fois","font","hors","ici","il","ils","je","juste",
"la","le","les","leur","là","ma","maintenant","mais","mes","mien","moins","mon","mot","même","ni","notre","nous","ou","où","par",
"parce","pas","peut","peu","plupart","pour","pourquoi",
"quand","que","quel","quelle","quelles","quels","qui","sa","sans","ses","seulement","si","sien","son","sont","sous","soyez","sur",
"ta","tandis","tellement","tels","tes","ton","tous",
"tout","trop","très","tu","voient","vont","votre","vous","vu","ça","étaient","état","étions","été","être", "un"]

In [45]:
# creating a list of stopwords for a specific text : with text most common words, and with french end english typical stopwords list
def stopwords_list(text,sw_nb):
    # Lemmatization
    text=text.lower()
    lemmatizer = WordNetLemmatizer()
    text=lemmatizer.lemmatize(text)
    
    # Tokenization
    words_list=nltk.word_tokenize(text)
    words_list= [word for word in words_list if word.isalnum()]
    
    # Suppress digits
    words_list=[w for w in words_list if w.isalpha()]
    
    # wordcount and stopwords
    word_counts = Counter(words_list)
    stopwords_list=[count[0] for count in word_counts.most_common(sw_nb)]
    
    sw = set()
    sw.update(stopwords_list)
    sw.update(tuple(nltk.corpus.stopwords.words('english')))
    sw=list(sw)
    # adding french stopwords
    for fsw in french_stopwords:
        sw.append(fsw)
    return sw

In [46]:
# Text lemmatization and tokenization
def tokenize_text(text):
    # Lemmatization
    text=text.lower()
    lemmatizer = WordNetLemmatizer()
    text=lemmatizer.lemmatize(text)
    
    # Tokenization
    words_list=nltk.word_tokenize(text)
    words_list= [word for word in words_list if word.isalnum()]
    
    # Suppress digits
    words_list=[lemmatizer.lemmatize(w) for w in words_list if w.isalpha()]
    return words_list

In [47]:
# definition of a wordcloud function to have a small visualisation
def word_cloud(words_list):
    wordcloud=WordCloud()
    sentence=' '.join(words_list)
    wordcloud.generate(sentence)
    # create a figure
    fig, ax = plt.subplots(1,1, figsize = (9,6))
    # add interpolation = bilinear to smooth things out
    plt.imshow(wordcloud, interpolation='bilinear')
    # and remove the axis
    plt.axis("off")

#### 1.2 Text pre-processing

In [48]:
text = (titles_reduced.iloc[:,1] + " " + titles_reduced.iloc[:,2] + " ").sum()

In [49]:
text

"Carmencita Documentary Short Le clown et ses chiens Animation Short Poor Pierrot Animation Comedy Romance Un bon bock Animation Short Blacksmith Scene Short Chinese Opium Den Short Corbett and Courtney Before the Kinetograph Short Sport Edison Kinetoscopic Record of a Sneeze Documentary Short Miss Jerry Romance Leaving the Factory Documentary Short Akrobatisches Potpourri Documentary Short The Arrival of a Train Documentary Short The Photographical Congress Arrives in Lyon Documentary Short The Waterer Watered Comedy Short Around a Cabin Animation Comedy Short Boat Leaving the Port Documentary Short Italienischer Bauerntanz Documentary Short Das boxende Känguruh Short Sport The Clown Barber Comedy Short The Derby 1895 Documentary Short Sport Blacksmith Scene Documentary Short The Sea Documentary Short Opening of the Kiel Canal News Short The Oxford and Cambridge University Boat Race News Short Sport The Messers. Lumière at Cards Documentary Short Cordeliers' Square in Lyon Documentary Short Fishing for Goldfish Documentary Short Baby's Meal Documentary Short Rough Sea at Dover Documentary Short Jumping the Blanket Documentary Short Die Serpentintänzerin Short Horse Trick Riders Documentary Short Arrivée d'un train gare de Vincennes Documentary Short Watering the Flowers Comedy Short Awakening of Rip Drama Short Sea Bathing Short The Ball Game Documentary Short Sport Barnet Horse Fair Short Barque sortant du port de Trouville Documentary Short Bataille de neige Comedy Documentary Short Bateau-mouche sur la Seine Documentary Short Batteuse à vapeur Documentary Short Le bivouac Short Les blanchisseuses Short Bois de Boulogne Documentary Short Boulevard des Italiens Documentary Short The Boxing Kangaroo Short Boxing Match; or, Glove Contest Short Sport Bébé et fillettes Documentary Short The Bohemian Encampment Documentary Short Ruraux au galop Documentary Short A Chegada do Comboio Inaugural à Estação Central do Porto Documentary Short A Merry-Go-Round Short Le chiffonnier Short Uma Corrida de Touros no Campo Pequeno Short Cortège de tzar allant à Versailles Documentary Short Cortège de tzar au Bois de Boulogne Documentary Short Coronation of a Village Maiden Short Dancing Darkies Comedy Documentary Short Dancing Girls Short Danse serpentine Short Dessinateur express Short Dessinateur: Chamberlain Short Dessinateur: Reine Victoria Short Dessinateur: Von Bismark Short Conjurer Making Ten Hats in Sixty Seconds Fantasy Short Unloading the Boat Documentary Short Post No Bills Comedy Short Demolition of a Wall Documentary Short Automobiles Starting a Race Short Sport Officers of French Army Leaving Service Short Effets de mer sur les rochers Documentary Short Enfants jouant sur la plage Documentary Short The Conjuring of a Woman at the House of Robert Houdin Horror Short Exit of Rip and the Dwarf Drama Short Le fakir, mystère indien Short Feira de Gado na Corujeira Documentary Short La gare Saint-Lazare Documentary Short Grandes manoeuvres Documentary Short Towing a Boat on the River Documentary Short A Hard Wash Comedy Short Les indiscrets Short Les ivrognes Short Gardener Burning Weeds Short Beach and Pier at Trouville, 1st part Documentary Short Beach and Pier at Trouville, 2nd part Documentary Short Market Day Documentary Short Leaving Jerusalem by Railway Documentary Short Libération des territoriaux Documentary Short The House of the Devil Horror Short Marée montante sur Brise-Larmes Documentary Short Melbourne Documentary Short Miss de Vere Short The Mysterious Paper Short Place Saint-Augustin Documentary Short Place de l'Opéra, First View Documentary Short Place de l'Opéra, Second View Documentary Short Place de la Bastille Documentary Short Place de la Concorde Documentary Short Place du théâtre français Documentary Short The Beach at Villiers in a Gale Short Smarter than the Teacher Short Pompiers à Lyon Documentary Short The Docks at Marseilles Documentary Short Retour au cantonnement Short Naval Review at Cherburg Documentary Short Rip Leaving Sleepy Hollow Drama Short Rip Meeting the Dwarf Fantasy Short Rip Passing Over the Mountain Fantasy Short Rip's Toast Drama Short Rip's Toast to Hudson Fantasy Short Rip's Twenty Years' Sleep Drama Short French Regiment Going to the Parade Documentary Short Réunion d'officiers Documentary Short Sac au dos Short Saída do Pessoal Operário da Fábrica Confiança Documentary Short Salut malencontreux d'un déserteur Short Rescue on the River, Pt. 2 Documentary Short Rescue on the River, Pt. 1 Documentary Short The Soldier's Courtship Comedy Short Closing Hours at Vibert's Perfume Factory Documentary Short Conjuring Short Tempête sur la jetée du treport Documentary Short The Terrible Railway Accident Short Tom Old Boot Short Les tribulations d'un concierge Comedy Short Academy for Young Ladies Short Un petit diable Short Une altercation au café Short A Terrible Night Comedy Horror Short Card Party Biography Short La voiture du potier Short The Wandering Negro Minstrels Music Short A Watermelon Feast Documentary Short Au réfectoire Comedy Short The Bewitched Inn Comedy Short L'aveugle Drama Short Baignade dans le torrent Documentary Short Ballet libella Documentary Short Buffalo Bill and Escort News Short Les cambrioleurs Comedy Short Chez le magnétiseur Comedy Short En classe Comedy Short Le cocher de fiacre endormi Comedy Short The Corbett-Fitzsimmons Fight Documentary News Sport Le Coucher d'Yvette Short Behind the Scenes Comedy Short Danse fleur de lotus Documentary Short Faust et Marguerite Short The Hallucinated Alchemist Fantasy Horror Short The Haunted Castle Horror Short Henley Regatta News Short Sport The Hypnotist at Work Short A Badly Managed Hotel Comedy Short Idylle Short Idylle interrompue Comedy Short The Devil's Laboratory Horror Short The Last Days of Pompeii Drama Short Leçon de danse Comedy Short Niagara Falls Documentary Short Le planton du colonel Comedy Short Le pêcheur dans le torrent Comedy Short Riña en un café Short Salida de los trabajadores de la fábrica España Industrial Documentary Short Salida de misa de doce del Pilar de Zaragoza Documentary Short Salida del público de la iglesia parroquial de Santa María de Sans Documentary Short Slagsmål i gamla Stockholm Short The Twins' Tea Party Comedy Short Une nuit agitée Comedy Short The X-Ray Fiend Comedy Horror Short Battle of Santiago Bay Short War Výstavní párkar a lepic plakátù Comedy Short A Sea Cave Near Lisbon Documentary Short Brittania Short The Burglar on the Roof Crime Short The Cavalier's Dream Fantasy Horror Short The Cave of the Demons Horror Short Le chemin de croix Short Cinderella Fantasy Short Come Along, Do! Comedy Short The Corsican Brothers Drama Short Cripple Creek Bar-Room Scene Short Western La crèche à Bethléem Short Le cuirassé Maine Short War La cène Short The Deserter Drama Short Dorotea Short Dostavenícko ve mlýnici Comedy Short Déménagement à la cloche de bois Short Ella Lola, a la Trilby Short L'entrée à Jérusalem Short Express Train on a Railway Cutting Documentary Short Les farces de Jocko Comedy Short Faust and Mephistopheles Fantasy Short La flagellation Short La fuite en Égypte Short Glasgow Fire Engine Short Gran corrida de toros Documentary Short Sport Indian War Council News Short Le jardin des oliviers Short Je vous y prrrrends! Short Jésus devant Pilate Short Leçons de boxe Comedy Short Sport Llegada de un tren a la estación de ferrocarril del Norte, de Barcelona Documentary Short London Express Documentary Short The Miller and Chimney Sweep Comedy Short Photographing a Ghost Fantasy Horror Short A Novice at X-rays Short The Astronomer's Dream; or, The Man in the Moon Comedy Fantasy Horror Saida do Paquete Duque de Braganca Short Scène d'escamotage Short Tearing Down the Spanish Flag Short War Smích a plác Documentary Short Visita de Doña María Cristina y Alfonso XIII a Barcelona News Short Waves and Spray Short L'affaire Dreyfus Biography Drama Short Aladdin and the Wonderful Lamp Fantasy Short The Artist and the Flower Girl Romance Short Aspectos da Praia de Cascais Documentary Short Au cabaret Comedy Short L'aveugle Short Battlefield Short Beauty and the Beast Family Fantasy Romance Boat Race Short Bombardment of Mafeking Drama Short War La bonne absinthe Short Casey at the Bat Comedy Short Sport Cinderella Drama Family Fantasy Portuguese Railway Train Documentary Short Le chiffonnier Comedy Short Choque de dos transatlánticos Animation Short Cleopatra's Tomb Horror Short Haggard's She: The Pillar of Fire Adventure Fantasy Horror Courte échelle Short Le crucifiement Short Les dangers de l'alcoolisme Drama Short Danse serpentine par Mme. Bob Walter Music Short Distributing a War Extra Documentary Short La descente de croix Short The Sign of the Cross Fantasy Horror Short Le déjeuner des enfants Comedy Short Erreur judiciaire Short The Haunted House Comedy Fantasy Horror A Turn of the Century Illusionist Fantasy Short King John Drama Short A Kiss in the Tunnel Comedy Romance Short The Legacy Short Llegada del vapor Bellver a Mallorca Documentary Short Matches: An Appeal Animation Short La mauvaise soupe Comedy Short The Miser's Doom Horror Short Monnaie de lapin Comedy Short Mésaventure d'un charbonnier Comedy Short Panorama from the Tower of the Brooklyn Bridge Documentary Short La résurrection Short Le tondeur de chiens Comedy Short Le tonnelier Comedy Short Transformations Comedy Short A Midnight Episode Comedy Horror Short Un lunch Comedy Short Vista de la entrada principal de la plaza de toros de Jerez, el segundo día de feria Documentary Short Summoning the Spirits Fantasy Horror Short Above the Limit Comedy Short Above the Speedway Documentary Short L'angélus Short L'arléquine Short Army Life; or, How Soldiers Are Made: Mounted Infantry Documentary Short Arrivée d'Arléquin Short Arrivée de Pierette et Pierrot Short As Seen Through a Telescope Comedy Short Attack on a China Mission Action Crime Drama Avenue de l'opéra Comedy Short Badinage Short Bataille d'oreillers Short Bataille de boules de neige Short Buffalo Bill's Show Parade Short Buffalo Bill's Wild West Parade News Short Buffalo Bill's Wild West Parade News Short Buffalo Bill's Wild West Show News Short Le bébé Short Chez le Maréchal-Ferrant Short Chez le photographe Short Chinese Magic Horror Short Chirurgie fin de siècle Comedy Horror Short The Clown and the Alchemist Comedy Fantasy Short La concierge Comedy Short Coucher d'une Parisienne Short Dance de l'ivresse Short Dans les coulisses Short Danse du papillon Documentary Short Danse du pas des foulards par des almées Short La danse du ventre Short Danse du voile Short Danse serpentine Documentary Short Danses Short Déclaration d'amour Short Le départ d'Arlequin et de Pierrette Short The Enchanted Drawing Animation Comedy Fantasy Faust and Marguerite Fantasy Horror Short La fée aux choux, ou la naissance des enfants Short Gavotte directoire Short Grandma's Reading Glass Family Short L'Habanera Short Hamlet, Duel Scene with Laertes Drama Short Happy Hooligan Comedy Short The House That Jack Built Short How It Feels to Be Run Over Comedy Short Chimmie Hicks and the Rum Omelet Comedy Short Le lapin Short Let Me Dream Again Comedy Short Leçon de danse Short Le marchand de coco Short Marché à la volaille Short Le matelot Short Eine moderne Jungfrau von Orleans Short Maple Leaf Viewing Horror Short Mort d'Adonis Short The Mystic Swing Fantasy Short Panorama de Barcelona: monumentos y fiestas Documentary Short Pas Japonais Short Pas de grâce Short Pas des éventails Short Pas du poignard Short La paysanne Short La petite magicienne Short Le Polichinelle Short La poupée noire Short La reine des jouets Short Retour des champs Documentary Short Le sang d'Adonis donnant naissance à la rose rouge Short Saut humidifié de M. Plick Comedy Short Soldiers of the Cross Biography Drama Short La source Short Spanish Bullfight Short Sport Suite de la danse Short La tarentelle Short Uncle Josh in a Spooky Hotel Comedy Fantasy Horror Uncle Josh's Nightmare Comedy Fantasy Short Une rage de dents Comedy Short Valse directoire Short Valse lente Short L'écossaise Short Another Job for the Undertaker Comedy Short Buffalo Bill's Wild West Parade Documentary News Short Charmant froufrou Short What Came Out of the Cheese; or, The Lilliputians in a New York Restaurant Comedy Short The Countryman's First Sight of the Animated Pictures Comedy Short Danses basques Short Day at the Circus Documentary Short Execution of Czolgosz with Panorama of Auburn Prison Drama History Short Exercício de Artilharia no Hipódromo de Belém Documentary Short Fire! Action Drama Short Frivolité Short The Haunted Curiosity Shop Comedy Fantasy Horror History of a Crime Crime Drama Short The India Rubber Head Comedy Fantasy Short Hussards et grisettes Short Lavatory moderne Short Lecture quotidienne Short Magical Sword Fantasy Romance Short Panorama of Esplanade by Night Documentary Short Parada de Bombeiros Documentary Short Uma Parada dos Alunos da Casa Pia de Lisboa Documentary Short Pas de colombine Short Little Red Riding Hood Fantasy Short A Road for Children's Bicycles in Barcelona Documentary Short Scrooge; or Marley's Ghost Drama Fantasy Horror Scène d'amour Short Scène d'ivresse Short The Devil's Seven Castles Drama Horror Short Tel est pris qui croyait prendre Short Uma Tourada à Antiga Portuguesa Documentary Short A táncz Documentary Short Undressing Extraordinary Comedy Fantasy Short Les vagues Short Visita de la escuadra inglesa a Barcelona Documentary Short Sleeping Beauty Drama Fantasy Short Buffalo Bill's Wild West Show News Short Carnaval en las ramblas Documentary Short Carreras de caballos en el hipódromo de Barcelona Documentary Short Miss Dundee and Her Performing Dogs Documentary Short Les clowns Comedy Short La cour des miracles Comedy Short The Coronation of King Edward VII History Short Danse excentrique Music Short Danse fantaisiste Short Danse mauresque Short La dent récalcitrante Comedy Short The Enchanted Cup Fantasy Short En faction Comedy Short Farces de cuisinière Comedy Short La fiole enchantée Short Fruits de saison Short La gavotte Short La gigue Short Jack and the Beanstalk Fantasy Short Le lion savant Comedy Short Le marchand de ballons Comedy Short Mother Goose Nursery Rhymes Comedy Short Le pommier Short Pour secouer la salade Short La première gamelle Comedy Short The Prince of Darkness Horror Short Procesión de las hijas de María de la parroquia de Sans Documentary Short Quadrille réaliste Short Midwife to the Upper Classes Comedy Short Demolishing and Building Up the Star Theatre Documentary Short Trompé mais content Comedy Short The Troublesome Fly Comedy Horror Short The Devil's Money Bags Comedy Fantasy Horror Uncle Josh at the Moving Picture Show Comedy Short A Peculiar Cabinet Short Alcohol and Its Victims Drama Short A Trip to the Moon Adventure Comedy Fantasy The Wild Man of Borneo Drama Short L'équilibriste Short Alice in Wonderland Family Fantasy Short Les apaches pas veinards Short Les aventures d'un voyageur trop pressé Short The Enchanted Box Fantasy Short Les braconniers Short Buffalo Bill's Parade Documentary Short Buffalo Bill's Street Parade Documentary Short Cake-walk de la pendule Short Carreras de bicicletas en el parque Documentary Short La chasse au cambrioleur Crime Drama Short A Chess Dispute Comedy Short Comme on fait son lit on se couche Short How Monsieur Takes His Bath Comedy Short Compagnons de voyage encombrants Short Dorothy's Dream Fantasy Short Enlèvement en automobile et mariage précipité Short An Extraordinary Cab Accident Comedy Short Faust and Mephistopheles Drama Horror Short Le fiancé ensorcelé Short The Great Train Robbery Action Adventure Crime La guirlande merveilleuse Fantasy Short Gulliver en el país de los gigantes Short Capital Execution Drama Short Hiawatha Adventure Drama Short Illusionniste renversant Short Jocko musicien Short Kit Carson Short Western Life of an American Fireman Action Short Le liqueur du couvent Short Lutteurs américains Short La main du professeur Hamilton ou le roi des dollars Short Mary Jane's Mishap Comedy Short The Messenger Boy's Mistake Comedy Romance Short Modelage express Short La mouche Short The Music Lover Comedy Music Short N.Y. Fire Department Returning Documentary Short Ne bougeons plus Short Nos bons étudiants Short Panorama of Riker's Island, N.Y. Documentary Short The Pioneers Short Western Potage indigeste Short La poule fantaisiste Short Puerto de Barcelona Documentary Short Rip Van Winkle Comedy Short The Kingdom of the Fairies Adventure Fantasy Short Répétition dans un cirque Short Secours aux naufragés Short Service précipité Short The Sick Kitten Comedy Family Short Les surprises de l'affichage Short Uncle Tom's Cabin Drama Short Uncle Tom's Cabin Drama Short La valise enchantée Short Le voleur sacrilège Short Voyage of the 'Arctic' Drama Short Après la fête Short L'assassinat du courrier de Lyon Drama Short Behind the Scenes Comedy Short Rum vs. Cherries Drama Short Le coffre enchanté Fantasy Short A Collier's Life Short Comment on disperse les foules Comedy Short Les deux rivaux Comedy Short Les enfants du miracle Short La gavotte de la reine Short A Gentleman of France Adventure Drama Short The Great Train Robbery Drama Short Western The Land Beyond the Sunset Drama Fantasy Short La leçon de pipeau Short L'oiseau envolé Short Opening the Williamsburg Bridge News Short Personal Comedy Short Pierrot, Murderer Short Le pompon malencontreux Short The Pearl Fisher Fantasy Short Railroad Smashup Action Short A Railway Tragedy Crime Short Rescued by Rover Crime Drama Family An Impossible Voyage Action Adventure Family The Abductors Drama Short Adventures of Sherlock Holmes Crime Drama Mystery Bohemios \\N Corrida de beneficencia celebrada por Quinito y Montes Documentary Short Coso y Paseo de Santa Engracia (Calles y plazas de Zaragoza) Documentary Short The Wig Chase Comedy Short The Effects of Too Much Scotch Drama Short Departure of Peary and the Roosevelt from New York News Short Desde el coso a la calle Cerdán (Calles y plazas de Zaragoza) Documentary Short The Inexperienced Chauffeur Comedy Short El dúo de la Africana Short Esmeralda Drama Short Funeral of Hiram Cronk Documentary News Short Gigantes y cabezudos Documentary Short Los guapos de la Vaquería del Parque Comedy Short El heredero de casa Pruna Comedy Short The Electric Hotel Animation Fantasy Sci-Fi El húsar de la guardia Short Juanito el forzudo Short The Kleptomaniac Crime Drama Short The Life of Charles Peace Biography Crime Short The Little Train Robbery Action Crime Drama The Moonshiners Action Drama Short Moose Hunting in Newfoundland Documentary Short New York Subway Documentary Short Hanging at Jefferson City Short Western Pennsylvania Tunnel Excavation Documentary Short Plaza de la Magdalena (Calles y plazas de Zaragoza) Documentary Short Raffles, the Amateur Cracksman Adventure Romance Short Reuben in the Opium Joint Comedy Short Se da de comer Comedy Short Los sitios de Chile Drama Short War Torrero y la ribera (Calles y plazas de Zaragoza) Documentary Short The Wooing and Wedding of a Coon Comedy Short The '?' Motorist Comedy Fantasy Sci-Fi The Anarchist's Mother-in-Law Comedy Short Apachentanz Short Arrival of Immigrants, Ellis Island Documentary Short Bilbao, Portugalete y los Altos Hornos Documentary Short Bonden i København Short Branden i Frihavnen Short Caros død Short Cerveza gratis Comedy Short Kong Christian d. IXs Bisættelse Documentary Short The Dancer's Dream Short Dream of a Racetrack Fiend Comedy Short Dream of a Rarebit Fiend Comedy Fantasy Short Ferias en San Sebastián y Cabalgata en la Ría Documentary Short Fiskerliv i Norden Short En foræring til min Kone Short Proklamationen af Kong Frederik d. VIII News Short Fæstningskrigen Short The Hand of the Artist Animation Short The Haunted Hotel Animation Comedy Fantasy Humorous Phases of Funny Faces Animation Comedy Family Den hvide sla

In [50]:
sw=stopwords_list(text,10)

In [51]:
sw[:10]

['ourselves',
 'and',
 'herself',
 "they're",
 'did',
 "we'll",
 'your',
 'drama',
 'will',
 "we've"]

In [52]:
words_list = tokenize_text(text)

In [53]:
words_list_wo_sw=[w for w in words_list if w not in sw]

In [54]:
words_list_wo_sw[:20]

['carmencita',
 'documentary',
 'clown',
 'chiens',
 'poor',
 'pierrot',
 'bock',
 'blacksmith',
 'scene',
 'chinese',
 'opium',
 'den',
 'corbett',
 'courtney',
 'kinetograph',
 'sport',
 'edison',
 'kinetoscopic',
 'record',
 'sneeze']