In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Data visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import cm

# Text Mining
import nltk
nltk.download('punkt')
from wordcloud import WordCloud
from collections import Counter
nltk.download('stopwords')
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('punkt_tab')

# warning management library
import warnings

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\smazo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\smazo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\smazo\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\smazo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [2]:
warnings.filterwarnings('ignore')
sns.set()
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

### 1. Loading of MSPT dataset and imbd titles

In [ ]:
mpst = pd.read_csv("../Raw_Data/mpst_full_data.csv")
# https://www.kaggle.com/datasets/cryptexcode/mpst-movie-plot-synopses-with-tags?resource=download

In [4]:
mpst.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14828 entries, 0 to 14827
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   imdb_id          14828 non-null  object
 1   title            14828 non-null  object
 2   plot_synopsis    14828 non-null  object
 3   tags             14828 non-null  object
 4   split            14828 non-null  object
 5   synopsis_source  14828 non-null  object
dtypes: object(6)
memory usage: 695.2+ KB

In [5]:
mpst.head()

     imdb_id                                          title                                      plot_synopsis                                               tags  split synopsis_source
0  tt0057603                        I tre volti della paura  Note: this synopsis is for the orginal Italian...          cult, horror, gothic, murder, atmospheric  train            imdb
1  tt1733125  Dungeons & Dragons: The Book of Vile Darkness  Two thousand years ago, Nhagruul the Foul, a s...                                           violence  train            imdb
2  tt0033045                     The Shop Around the Corner  Matuschek's, a gift store in Budapest, is the ...                                           romantic   test            imdb
3  tt0113862                             Mr. Holland's Opus  Glenn Holland, not a morning person by anyone'...             inspiring, romantic, stupid, feel-good  train            imdb
4  tt0086250                                       Scarface  In May 1980, a Cuban man named Tony Montana (A...  cruelty, murder, dramatic, cult, violence, atm...    val            imdb

In [ ]:
titles = pd.read_csv("../Raw_Data/title.basics.tsv", sep='\t', nrows = 10000)
#https://developer.imdb.com/non-commercial-datasets/

In [8]:
titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tconst          10000 non-null  object
 1   titleType       10000 non-null  object
 2   primaryTitle    10000 non-null  object
 3   originalTitle   10000 non-null  object
 4   isAdult         10000 non-null  int64
 5   startYear       10000 non-null  object
 6   endYear         10000 non-null  object
 7   runtimeMinutes  10000 non-null  object
 8   genres          10000 non-null  object
dtypes: int64(1), object(8)
memory usage: 703.3+ KB

In [9]:
titles.head()

      tconst titleType            primaryTitle           originalTitle  isAdult startYear endYear runtimeMinutes                    genres
0  tt0000001     short              Carmencita              Carmencita        0      1894      \N              1         Documentary,Short
1  tt0000002     short  Le clown et ses chiens  Le clown et ses chiens        0      1892      \N              5           Animation,Short
2  tt0000003     short            Poor Pierrot          Pauvre Pierrot        0      1892      \N              5  Animation,Comedy,Romance
3  tt0000004     short             Un bon bock             Un bon bock        0      1892      \N             12           Animation,Short
4  tt0000005     short        Blacksmith Scene        Blacksmith Scene        0      1893      \N              1                     Short